learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('logs.urls', namespace='logs')),
    url(r'^users/', include('users.urls', namespace='users')),
]

logs/urls.py
# coding:utf-8
__author__ = 'PieLs'

from django.conf.urls import url
from logs import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    # 用于编辑条目的页面
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
# _*_ coding:utf-8 _*_
__author__ = 'PieLs'

from django.conf.urls import url
from django.contrib.auth.views import login

from users import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

logs/models.py
# coding:utf-8
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    '''
    用户学习的主题
    '''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    class Meta:
        verbose_name_plural = u'主题'

    def __unicode__(self):
        '''
        返回模型的字符串表示
        '''
        return self.text

class Entry(models.Model):
    '''
    学到的有关某个主题的具体知识
    '''
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = u'详情'

    def __unicode__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

logs/forms.py
# _*_ coding:utf-8 _*_
__author__ = 'PieLs'

from django import forms
from logs.models import Topic, Entry


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

logs/views.py
# coding:utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from logs.models import Topic, Entry
from logs.forms import TopicForm, EntryForm
# Create your views here.

def index(request):
    return render(request, 'logs/index.html')

@login_required
def topics(request):
    '''
    显示所有的主题
    '''
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'logs/topics.html', context)

@login_required
def topic(request, topic_id):
    '''
    显示单个主题以及其所有的条目
    '''
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {
        'topic': topic,
        'entries': entries
    }
    return render(request, 'logs/topic.html', context)

@login_required
def new_topic(request):
    '''
    添加新主题
    '''
    if request.method != 'POST':
        form = TopicForm()
    else:
        # POST提交的数据
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('logs:topics'))

    context = {"form": form}
    return render(request, 'logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    '''
    在特定的主题下添加新条目
    '''
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    '''
    编辑既有条目
    '''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初次请求,使用既有条目填充表单
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'logs/edit_entry.html', context)

users/views.py
# coding:utf-8
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    '''
    注销用户
    '''
    logout(request)
    return HttpResponseRedirect(reverse('logs:index'))

def register(request):
    '''
    注册新用户
    '''
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

templates/logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, inital-scale=1">
        <title>Learning Log</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
    <body>
        <!--Static bavbar-->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="nav-header">
                    <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    </button>
                    <a class="navbar-brand" href="{% url 'logs:index' %}">
                        Learning Log
                    </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'logs:topics' %}">Topics</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                            <li><a>Hello,{{ user.username }}.</a></li>
                            <li><a href="{% url 'users:logout' %}">Log out</a></li>
                        {% else %}
                            <li><a href="{% url 'users:register' %}">register</a></li>
                            <li><a href="{% url 'users:login' %}">login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}
            {% endblock header %}
        </div>
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </div>
    </body>
</html>

templates/logs/edit_entry.html
{% extends 'logs/base.html' %}
{% block content %}
    <p><a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Edit entry:</p>
    <form action="{% url 'logs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
    </form>
{% endblock content %}

templates/logs/index.html
{% extends "logs/base.html" %}
{% block header %}
    <div class="jumbotron">
        <h1>Track your learning.</h1>
    </div>
{% endblock %}
{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a>to make your own Learning Log, and list the topics
        you're learning about.
    </h2>
    <h2>
        Whenever you learning something new about a topic, make an entry summarizing what you're learned.
    </h2>
{% endblock %}

templates/logs/new_entry.html
{% extends 'logs/base.html' %}
{% block content %}
    <p><a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Add a new entry:</p>
    <form action="{% url 'logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add entry</button>
    </form>
{% endblock content %}

templates/logs/new_topic.html
{% extends 'logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>Add a new topic:</h2>
{% endblock %}
{% block content %}
    <form action="{% url 'logs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
    </form>
{% endblock %}

templates/logs/topic.html
{% extends 'logs/base.html' %}
{% block header %}
    <h2>{{ topic }}</h2>
{% endblock %}

{% block content %}
    <p>
        <a href="{% url 'logs:new_entry' topic.id %}">add new entry</a>
    </p>
    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added }}
                    <small>
                        <a href="{% url 'logs:edit_entry' entry.id %}">edit entry</a>
                    </small>
                </h3>
            </div>
        <div class="panel-body">
            {{ entry.text | linebreaks }}
        </div>
        </div>
    {% empty %}
        There are no entries for this topic yet.
    {% endfor %}

{% endblock %}

templates/logs/topics.html
{% extends 'logs/base.html' %}
{% block header %}
    <h1>Topics</h1>
{% endblock %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'logs:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
            {% empty %}
                <li>No topics have been added yet.</li>
        {% endfor %}

    </ul>
    <h3><a href="{% url 'logs:new_topic' %}">Add new topic</a></h3>
{% endblock %}

templates/users/login.html
{% extends 'logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
    <h2>Log in to your account.</h2>
{% endblock %}

{% block content %}
    <form action="{% url 'users:login' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'logs:index' %}" />
    </form>
{% endblock content %}

templates/users/register.html
{% extends 'logs/base.html' %}
{% block content %}
    <form action="{% url 'users:register' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">register</button>
        <input type="hidden" name="next" value="{% url 'logs:index' %}" />
    </form>
{% endblock content %}